### ISSUE TITLE
Not deploy installation guide

### ISSUE THREAD

**Issue by carlofraue79** [chetans9/core-php-admin-panel#18]
Into project and Readme. MD are not written the steps to install the application.
It is not bug but some steps to install it should be appreciated

**Comment by ryan-andri** [comment]
> Into project and Readme. MD are not written the steps to install the application.
> It is not bug but some steps to install it should be appreciated

just install xampp and clone this repo to htdocs folder then configure by yourself.

**Comment by vlori2k** [comment]
what if i have the project locally on my own server but the database is placed somewhere else such as Amazon webservices etc? I changed the config file but does not work ..
