### ISSUE TITLE
How to add new user ? No doc/guide

### ISSUE THREAD

**Issue by aravindnc** [chetans9/core-php-admin-panel#19]

**Comment by gmhz** [comment]
there's corephpadmin.sql file

**Comment by fferraro87** [comment]
yes but password is hashed, so how can i add a new admin?

**Comment by aravindnc** [comment]
You have to generate password using the same algorithm then replace it in the db. that is the only way I found out.

**Comment by gmhz** [comment]
login superadmin
password superadmin

**Comment by samuelrajs** [comment]
why am i not able to add a new user through the UI ( front end) ?

**Comment by ghost** [comment]
Front end's not implemented
https://github.com/chetans9/core-php-admin-panel/issues/30
