### ISSUE TITLE
Update record

### ISSUE THREAD

**Issue by Zeroema** [chetans9/core-php-admin-panel#2]
Hello,

First thanks for this wonderful php admin panel. One question, when I create a new element in the side bar, and I tried to make the update option works, always show the same record not matter wich row I selected. What I´m doing wrong?

**Comment by chetans9** [comment]
make sure you have added query string parameters on links to update records e.g update.php?customer_id=61&operation=edit . 

keep "name" attribute of input type same  as database column name.  

then use 
$data_to_update = filter_input_array(INPUT_POST);
    $db->where('id',$customer_id);
   $db->update('customers', $data_to_update);

**Comment by Zeroema** [comment]
Hello Chetans9,

Thank you for your support and quick answer.

Done. I found the problem. I changed the value of "id" from a number to a Mac address but the FILTER_VALIDATE_INT was causing the problem.

Something new that I detected is that when you click on save button to save the changes in the MySQL table, in the php the changes goes back to the original.

e.g
![edit store value](https://user-images.githubusercontent.com/20746088/33294237-4ce409dc-d395-11e7-82fc-3365b164b8af.PNG)
![after click in save button](https://user-images.githubusercontent.com/20746088/33294239-5069ae90-d395-11e7-87f0-3c59695fb40f.PNG)

**Comment by chetans9** [comment]
Ok. I got it. Thanks for pointing it out. After Updating/Inserting Redirect to same page and show a session flash message.

Like this : 

```
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
   
    $data_to_update = filter_input_array(INPUT_POST);
    $db->where('id',$customer_id);
    $stat = $db->update('customers', $data_to_update);

    if($stat){
        $_SESSION['success'] = "Customer updated successfully!";
        header('location: customers.php'); //Redirect after successfull update
        exit();
    }
}
```

and whatever page you are redirecting Add something like this

`if(isset($_SESSION['success']))
{
echo '<div class="alert alert-success alert-dismissable">
   		<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
    		<strong>Success! </strong>'. $_SESSION['success'].'
  	  </div>';
  unset($_SESSION['success']);
}
`


I was a newbie when I built this. I will fix it in later commits..
