### ISSUE TITLE
distinct select method not working

### ISSUE THREAD

**Issue by remyamr** [chetans9/core-php-admin-panel#25]
distinct select method not working

**Comment by ghost** [comment]
Can you provide more informations?

**Comment by remyamr** [comment]
need to select distinct bankname from table https://github.com/bhavyanshu/indian-bank-ifsc-branch-database-sql/blob/master/bank_details.sql

**Comment by remyamr** [comment]
$select = array(distinct('bank_name)','bank_id');
$rows = $db->arraybuilder()->paginate('tbl_bank_details', $page, $select);
not working

**Comment by ghost** [comment]
This issue is releated to this libary https://github.com/ThingEngineer/PHP-MySQLi-Database-Class, that's used in this project.
I sugest you to check the documentatios of the libary

**Comment by ryan-andri** [comment]
@remyamr distinct('bank_name)' ?
should be distinct('bank_name')

**Comment by remyamr** [comment]
No thats not a issue..

> @remyamr distinct('bank_name)' ?
> should be distinct('bank_name')
