### ISSUE TITLE
checkbox values encountering error

### ISSUE THREAD

**Issue by remyamr** [chetans9/core-php-admin-panel#26]
<label> <input type="checkbox" name="**service_id[]**" value="1"/> Fashion </label>
<label> <input type="checkbox" name="**service_id[]**" value="2"/> Fashion1 </label>
<label> <input type="checkbox" name="**service_id[]**" value="3"/> Fashion2 </label>

cannot pass multiple values with name "service_id[]" in checkbox its shows error field not existing.. 

name with name "service_id" working , but i need to pass multiple values

**Comment by ghost** [comment]
Hi @remyamr , did you find a solution?

**Comment by remyamr** [comment]
yes

**Comment by ghost** [comment]
Could you share, so we implemente this on this project?
