### ISSUE TITLE
register - super admin

### ISSUE THREAD

**Issue by Amirhf1** [chetans9/core-php-admin-panel#27]
how to register for the first time super admin ؟

**Comment by ghost** [comment]
You need to create an database and import the "corephpadmin.sql" file to it.
An super admin is created with "superadmin" both for username and password.
Don't forget to config the "config/config.php" file to connect to your database.

**Comment by Amirhf1** [comment]
Yes, I did all three of those things.
My database has been successfully connected but I can't login , And I can't make a new user
@peixespnsc

**Comment by ghost** [comment]
Some error is displayed?

**Comment by codifydevelopers** [comment]
I can't log in as
username: admin
password: admin 
in localhost
