### ISSUE TITLE
need between condition query

### ISSUE THREAD

**Issue by remyamr** [chetans9/core-php-admin-panel#28]
I nee to know how select data between two **dates** and equal to id given

Date in my db look likes 2019-11-24 07:51:05

Post date like  - 2019-11-14 and 2019-11-24

  $db->where('o_id', $o_id);
  $numorders = $db->getValue("tbl_orders", "count(*)");

**Comment by ghost** [comment]
Hi @remyamr,
This project uses the https://github.com/ThingEngineer/PHP-MySQLi-Database-Class as DB library. Please send yours questions about DB queries to they
