### ISSUE TITLE
Need to register user page

### ISSUE THREAD

**Issue by mahdi5574** [chetans9/core-php-admin-panel#30]
Hi.
Thanks for your great code.
I need a register page for users. How can I add this page?

**Comment by ghost** [comment]
Hi @mahdi5574 ,
I'm not sure what you ask, but after you login, go to <yoursite>/admin_users.php
Your "admin_type" must to be "super" to have access to this page

**Comment by mahdi5574** [comment]
Hi.
I need user registration page with your code.

**Comment by felipeabranches** [comment]
You mean this code https://github.com/chetans9/core-php-admin-panel/blob/master/admin_users.php?

**Comment by mahdi5574** [comment]
No.
I mean a user (not admin) can register himself without admin
privileges from a registration link such as this:
mywebsite.com/user_register.php .
And second question is : how can I limit left menu items to some admins ?

**Comment by felipeabranches** [comment]
In this branch https://github.com/peixespnsc/core-php-admin-panel you can register users without Superadmin or Admin privileges, but there isn't a form where a user can register himself yet.
There's also the possibility to create others users' groups and change their privileges.

To limit the access of some menu itens (whit the forementioned forked below) you need to check the user's group, like this:

```
<?php if ($_SESSION['id_group'] == 2 || $_SESSION['id_group'] == 3): ?>
<!-- Only Moderator and Administrator groups have access -->
<li>
	<a href="#"><i class="fa fa-users fa-fw"></i> Users<i class="fa arrow"></i></a>
	<ul class="nav nav-second-level">
		<li><a href="<?php echo $base_url; ?>/users/accounts.php"><i class="fa fa-list fa-fw"></i> Accounts</a></li>
		<li><a href="<?php echo $base_url; ?>/users/groups.php"><i class="fa fa-list fa-fw"></i> Groups</a></li>
	</ul>
</li>
<?php endif; ?>
```

**Comment by mahdi5574** [comment]
thanks for your great help.
I created a column in users table and named it GID. And I
defined $_SESSION['GID'] = $row['GID']; in login.php.
after run your code I got this erro: " Notice: Undefined index: GID in
C:\xampp\htdocs\abfa\includes\header.php on line 83
line 83 in header.php is: <?php if ($_SESSION['GID'] == 0 ||
$_SESSION['GID'] == 2): ?>

**Comment by felipeabranches** [comment]
Try to define $_SESSION['GID'] = $row['GID']; in authenticate.php file too, on line 24.
Tell me if it works

**Comment by mahdi5574** [comment]
Hi.
Thanks again for your code (php dashboard).
I need to change form validation error messages. exactly this error:
"Please fill out this field."
Thanks a lot
