### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by subtain-haider** [chetans9/core-php-admin-panel#32]
downloaded the zip extracted it, imported SQL into my database, opened  the project in xampp and now on login page

using following credentials:
username: admin
password: admin

its always saying "Invalid user name or password"

I have also tried using different usernames in users table bt nothing works

wht are the credentials???
and is there any way I can pass authentication initially or change the password???

**Comment by robloves** [comment]
Comment out lines 10 to 15 from /lib/Users/Users.php and lines 6 to 8 from includes/auth_validate.php.
After that you can add a new admin via add_admin.php and logon.

Don't forget to uncomment the lines in both files afterwards.
