### ISSUE TITLE
not remove html specjal charaketers

### ISSUE THREAD

**Issue by GorlikItsMe** [chetans9/core-php-admin-panel#5]
http://corephpadmin.000webhostapp.com/add_customer.php
i can add <b>big name</b> and more html code. its realy dangerous because i can add javascript and i can make lots off errors, bugs, and more. i can create malevare on site.

**Comment by chetans9** [comment]
Issue solved.

**Comment by mufeedvh** [comment]
Hello @chetans9,

I bypassed the issue fixes and was able to successfully escalate these vulnerabilities. As your fix wasn't able to resolve the issue, I've contributed to the project by securing every vulnerable input handling thus resolving this issue perfectly :). :+1: 

Fix those ASAP as it's critical and this is an admin panel used by several people. :)

# My Fixes (Contribution):
#16 
#15 
#14 
#13 

Best Regards,
Mufeed VH (@mufeedvh)
