### ISSUE TITLE
Rework Login

### ISSUE THREAD

**Issue by CeeBeeSco** [chetans9/core-php-admin-panel#7]
So after looking at the code for the login some HUGE security issues have come up! 

- MD5 on the passwords! HUGE no no... Use password_hash()!
- Storing the password as a cookie and using that to remember the user! Means I only need the hash to get into an account! Easy with a MITM attack. 

Other than that its all very good!

**Comment by Tayyabrana** [comment]
I am working on this admin but getting an issue on adding customer from customer form

I am trying to resolve this issue if anyone have already resolved this please tell me
Or 
If only i am getting this issue please tell me!

Thanks in Advance

**Comment by chetans9** [comment]
Login has been reworked.

**Comment by chetans9** [comment]
Password hash and secure remember me implemented.
