### ISSUE TITLE
Insert is not working in Customer

### ISSUE THREAD

**Issue by Tayyabrana** [chetans9/core-php-admin-panel#8]
I am working on this admin but getting an issue on adding customer from customer form

I am trying to resolve this issue if anyone have already resolved this please tell me
Or
If only i am getting this issue please tell me!

Thanks in Advance

**Comment by chetans9** [comment]
Hi,
You must be using Mysql In strict Mode which is doesn't allow blank values for "Not null" columns. Issue will be fixed in next commit. 
 
Thanks

**Comment by Tayyabrana** [comment]
Thank you very much for your ans!!!!

I'll be awaiting for next commit

**Comment by chetans9** [comment]
> I am working on this admin but getting an issue on adding customer from customer form
> 
> I am trying to resolve this issue if anyone have already resolved this please tell me
> Or
> If only i am getting this issue please tell me!
> 
> Thanks in Advance

Issue resolved. Pull changes and import new database using corephpadmin.sql

**Comment by Tayyabrana** [comment]
Thank You so much for solving my issue and telling me the problem.

I am just a junior developer and don't know these things but you helped me a lot by contributing this code.

You are great helper for me!
May god bless you!
