### ISSUE TITLE
login.php is not working, entered login and passwd saying incorrect.

### ISSUE THREAD

**Issue by sharipovshoxrux** [chetans9/core-php-admin-panel#9]
entered login and passwd of admins into mysql manually, after that typed login and passwd credentials saying incorrect

**Comment by chetans9** [comment]
Is your manually entered password password_hash() encrypted?

**Comment by sharipovshoxrux** [comment]
yup, I entered it manually

**Comment by sharipovshoxrux** [comment]
Can u describe the process more specifically that how should I entered the password_hash manually?

**Comment by chetans9** [comment]
In any PHP script get the result of password_hash('your_password',PASSWORD_DEFAULT); and update the "passwd" column with the result.

**Comment by sharipovshoxrux** [comment]
thanks I got it
